version: "2"
services:
  web:
    build:
      context: ./dockerfiles/elegant-ci
    container_name: elegant-ci
    depends_on:
      - rabbitmq
    ports:
      - "80:8080"
    volumes:
      - ./dockerfiles/elegant-ci/elegant_ci:/var/lib/elegant_ci
    links:
      - rabbitmq
    environment:
      - RABBITMQ_NODE_IP_ADDRESS=rabbitmq
      - RABBITMQ_NODE_PORT=5672
    working_dir: /var/lib/elegant_ci
    command: mix deps.clean && mix get.deps && mix run --no-halt

  rabbitmq:
    build:
      context: ./dockerfiles/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672"
